name: notes_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  waterfall_flow: ^3.1.0
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.2
  intl: ^0.20.2
  shimmer: ^3.0.0

  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
